# Generated by Django 3.2.9 on 2021-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='disgust_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
    ]
